kubemanager:
  hosts:
    km1:  # proxmox vms
      ansible_host: 192.168.5.201
    km2:  # proxmox vms
      ansible_host: 192.168.5.202
    km3:  # proxmox vms
      ansible_host: 192.168.5.203

kubeworker:
  hosts:
    192.168.5.22[1:3]:    # proxmox vms
    192.168.5.227:        # proxmox vm
    192.168.5.51:         # rpi
      ansible_become: true



kubeall:
  children:
    kubemanager:
    kubeworker:
