- name: Restart service after package update
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - apache2
    - nginx
    - mysql
  when: ansible_service_mgr == "systemd"
