- name: Update and clean Ubuntu packages
  hosts: ubuntu
  become: true

  roles:
    - common
  # showing the tasks in the common role for reference
  # tasks:
  #   - name: Update package list
  #     ansible.builtin.apt:
  #       update_cache: true

  #   - name: Upgrade all packages
  #     ansible.builtin.apt:
  #       upgrade: dist

  #   - name: Remove unnecessary packages
  #     ansible.builtin.apt:
  #       autoremove: true
  #       purge: true
