# setup kubernetes rke2 on the manager and worker nodes


- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - role: setup-network-forwarding
    - role: rke2-download

# Creates RKE2 bootstrap manifests folder and copies kube-vip template over (configured with variables)
- name: Deploy Kube VIP
  hosts: kubemanager
  gather_facts: true
  roles:
    - role: kube-vip

- name: Prepare RKE2 on Servers and Agents
  hosts: kubeall
  gather_facts: true
  roles:
    - role: rke2-prepare

# Adds additional servers using the token from the previous task
- name: Add additional RKE2 Servers
  hosts: kubemanager
  gather_facts: true
  roles:
    - role: add-server

# Adds agents to the cluster
- name: Add additional RKE2 Agents
  hosts: kubeworker
  gather_facts: true
  roles:
    - role: add-agent
